---
abstract: 'Create tests from custom L<Mojolicious> templates'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Test-CreateFromMojoTemplates
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla::File::InMemory: '5.000'
  Dist::Zilla::Role::FileGatherer: '5.000'
  File::Find::Rule: '0.33'
  MojoX::CustomTemplateFileParser: '0.02'
  Moose: '2.00'
  Path::Tiny: '0.050'
  namespace::sweep: '0.006'
  perl: '5.010'
resources:
  bugtracker: https://github.com/Csson/p5-dist-zilla-plugin-test-createfrommojotemplate/issues
  homepage: https://github.com/Csson/p5-dist-zilla-plugin-test-createfrommojotemplate
  repository: https://github.com/Csson/p5-dist-zilla-plugin-test-createfrommojotemplate.git
version: '0.02'
